"""Discussion filtering helpers for gitlab-mcp."""

from typing import Any


def is_user_discussion(discussion: dict[str, Any]) -> bool:
    """Check if a discussion is user-created (not a system note).

    Args:
        discussion: GitLab discussion object

    Returns:
        True if discussion is user-created, False if it's a system note

    Note:
        - Returns False for empty discussions (defensive programming)
        - System notes are auto-generated by GitLab (assignments, labels, etc.)
        - Checks the first note since it determines the discussion type
        - Defaults to True if 'system' field is missing (backward compatible)
    """
    notes = discussion.get("notes", [])
    if not notes:
        return False

    # Check if the first note is a system note
    # Default to False (not a system note) if field is missing (defensive)
    first_note = notes[0]
    return not first_note.get("system", False)


def filter_actionable_discussions(discussions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Filter discussions to only include actionable user discussions.

    Returns discussions that are:
    1. User-created (not system-generated)
    2. Resolvable (can be resolved - excludes individual_note comments)
    3. Unresolved (need attention)

    Args:
        discussions: List of GitLab discussion objects

    Returns:
        Filtered list containing only unresolved user discussions
    """
    result = []
    for d in discussions:
        if not is_user_discussion(d):
            continue
        first_note = d.get("notes", [{}])[0]
        # Only count as unresolved if the note is resolvable AND not resolved
        # Notes with resolvable=false (like individual_note comments) can never be resolved
        if first_note.get("resolvable", False) and not first_note.get("resolved", False):
            result.append(d)
    return result
